#!/bin/sh
docker tag  	gcr.io/google_containers/kube-apiserver-amd64:v1.8.6	  	jerryduren/kube-apiserver-amd64:v1.8.6              
docker tag  	gcr.io/google_containers/kube-controller-manager-amd64:v1.8.6	  	jerryduren/kube-controller-manager-amd64:v1.8.6              
docker tag  	gcr.io/google_containers/kube-proxy-amd64:v1.8.6	  	jerryduren/kube-proxy-amd64:v1.8.6              
docker tag  	gcr.io/google_containers/kube-scheduler-amd64:v1.8.6	  	jerryduren/kube-scheduler-amd64:v1.8.6              
docker tag  	gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.1	  	jerryduren/kubernetes-dashboard-amd64:v1.8.1              
docker tag  	quay.io/coreos/flannel:v0.9.1	  	jerryduren/flannel:v0.9.1              
docker tag  	quay.io/coreos/flannel:v0.9.1-amd64	  	jerryduren/flannel:v0.9.1-amd64        
docker tag  	quay.io/calico/node:v2.6.2	  	jerryduren/node:v2.6.2              
docker tag  	quay.io/calico/cni:v1.11.0	  	jerryduren/cni:v1.11.0             
docker tag  	gcr.io/google_containers/kube-controller-manager-amd64:v1.8.0	  	jerryduren/kube-controller-manager-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/kube-apiserver-amd64:v1.8.0	  	jerryduren/kube-apiserver-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/kube-scheduler-amd64:v1.8.0	  	jerryduren/kube-scheduler-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/kube-scheduler-amd64:v1.8.6	  	jerryduren/kube-scheduler-amd64:v1.8.6              
docker tag  	gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.1	  	jerryduren/kubernetes-dashboard-amd64:v1.8.1              
docker tag  	quay.io/coreos/flannel:v0.9.1	  	jerryduren/flannel:v0.9.1              
docker tag  	quay.io/coreos/flannel:v0.9.1-amd64	  	jerryduren/flannel:v0.9.1-amd64        
docker tag  	quay.io/calico/node:v2.6.2	  	jerryduren/node:v2.6.2              
docker tag  	quay.io/calico/cni:v1.11.0	  	jerryduren/cni:v1.11.0             
docker tag  	gcr.io/google_containers/kube-controller-manager-amd64:v1.8.0	  	jerryduren/kube-controller-manager-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/kube-apiserver-amd64:v1.8.0	  	jerryduren/kube-apiserver-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/kube-scheduler-amd64:v1.8.0	  	jerryduren/kube-scheduler-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/kube-proxy-amd64:v1.8.0	  	jerryduren/kube-proxy-amd64:v1.8.0              
docker tag  	gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5	  	jerryduren/k8s-dns-sidecar-amd64:1.14.5              
docker tag  	gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5	  	jerryduren/k8s-dns-kube-dns-amd64:1.14.5              
docker tag  	gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5	  	jerryduren/k8s-dns-dnsmasq-nanny-amd64:1.14.5              
docker tag  	gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3	  	jerryduren/heapster-influxdb-amd64:v1.3.3              
docker tag  	gcr.io/google_containers/heapster-grafana-amd64:v4.4.3	  	jerryduren/heapster-grafana-amd64:v4.4.3              
docker tag  	gcr.io/google_containers/heapster-amd64:v1.4.2	  	jerryduren/heapster-amd64:v1.4.2              
docker tag  	gcr.io/google_containers/etcd-amd64:3.0.17	  	jerryduren/etcd-amd64:3.0.17              
docker tag  	gcr.io/google_containers/pause-amd64:3.0	  	jerryduren/pause-amd64:3.0             
docker tag  	gcr.io/google_containers/kube-proxy-amd64:v1.8.6	  	jerryduren/kube-proxy-amd64:v1.8.6             
docker tag  	gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.1	  	jerryduren/kubernetes-dashboard-amd64:v1.8.1             
docker tag  	gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.0	  	jerryduren/kubernetes-dashboard-amd64:v1.8.0             
docker tag  	quay.io/coreos/flannel:v0.9.1	  	jerryduren/flannel:v0.9.1             
docker tag  	quay.io/coreos/flannel:v0.9.1-amd64	  	jerryduren/flannel:v0.9.1-amd64       
docker tag  	quay.io/calico/node:v2.6.2	  	jerryduren/node:v2.6.2             
docker tag  	quay.io/calico/cni:v1.11.0	  	jerryduren/cni:v1.11.0            
docker tag  	gcr.io/google_containers/kube-proxy-amd64:v1.8.0	  	jerryduren/kube-proxy-amd64:v1.8.0             
docker tag  	gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3	  	jerryduren/heapster-influxdb-amd64:v1.3.3             
docker tag  	gcr.io/google_containers/heapster-grafana-amd64:v4.4.3	  	jerryduren/heapster-grafana-amd64:v4.4.3             
docker tag  	gcr.io/google_containers/heapster-amd64:v1.4.2	  	jerryduren/heapster-amd64:v1.4.2             
docker tag  	gcr.io/google_containers/pause-amd64:3.0	  	jerryduren/pause-amd64:3.0                
docker tag  	radial/busyboxplus:curl	  	jerryduren/busyboxplus:curl               
